sky:
  datasource:
    driver-class-name: org.postgresql.Driver
    host: localhost
    port: 5432
    database: sky_take_out
    username: postgres
    password: 123456
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-secret: MeXl4NmvZXBufxeMuZgDQ7eSfKPFTN
    access-key-id: LTAI5tLwB3fBtJGEgZLQEXsW
    bucket-name: pierces
  redis:
    host: localhost
    port: 6379
    password:
    database: 10
  wechat:
    appid: wx0fa355eb765ced46
    secret: b006292f2e6fc7d03eb2fe5d5825f769